export default {
    A: 'fas fa-font',
    ARROW_LEFT_CIRCLE: 'glyphicon glyphicon-circle-arrow-left',
    BELL: 'fa fa-bell',
    CHECK: 'glyphicon glyphicon-ok',
    NEW_WINDOW: 'glyphicon glyphicon-new-window',
    BOLD: 'fas fa-bold',
    LIST: 'glyphicon glyphicon-th-list',
    STOP : 'glyphicon glyphicon-stop',
    SCISSORS: 'glyphicon glyphicon-scissors',
    SUNGLASSES: 'glyphicon glyphicon-sunglasses',
    RETWEET: 'glyphicon glyphicon-retweet',
    DOWNLOAD: 'glyphicon glyphicon-download-alt',
    THRASH: 'fas fa-trash',
    IMAGES: 'fa fa-images',
    EXIT: 'fas fa-sign-out-alt',
    ZOOM_OUT: 'glyphicon glyphicon-zoom-out action',
    ZOOM_IN: 'glyphicon glyphicon-zoom-in action',
    PICTURE: 'glyphicon glyphicon-picture',
    ALIGN_LEFT: 'fas fa-align-left',
    ALIGN_RIGHT: 'fas fa-align-right',
    ALIGN_CENTER: 'fas fa-align-center',
    TEXT_COLOR: 'glyphicon glyphicon-text-color',
    REMOVE: 'glyphicon glyphicon-remove',
    SEARCH: 'glyphicon glyphicon-search',
    UPLOAD: 'fas fa-upload',
    CHAT: 'glyphicon glyphicon-chat',
    CLOSE: 'glyphicon glyphicon-close',
    TRASH: 'fas fa-trash',
    THUMBS_UP: 'glyphicon glyphicon-thumbs-up',
    THUMBS_DOWN: 'glyphicon glyphicon-thumbs-down',
    ERROR: 'glyphicon glyphicon-ban-circle',
    LAMP: 'glyphicon glyphicon-lamp',
    TEXT_SIZE: 'fas fa-text-height',
    MINUS: 'fas fa-minus',
    PLUS: 'fas fa-plus'

}